export interface Respuesta {
    success: string,
    error: string,
    code: any,
    books: [],
    updates: [],
    other_updates: [],
    random: any,
    code_update: string,
    code_books: string,
    code_random: string,
    token: string,
    user: any,
    chapter: any,
    chapters: Array<any>,
    after: any,
    before: any,
    book: any,
    imageName: string
}