import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { BrowserAnimationsModule } 
from '@angular/platform-browser/animations';
import { LayoutModule } from '@angular/cdk/layout';
import { OverlayModule } from '@angular/cdk/overlay';
import { 
    MatButtonModule,
    MatToolbarModule,
    MatSidenavModule,
    MatInputModule,
    MatFormFieldModule,
    MatDividerModule,
    MatListModule,
    MatTabsModule,
    MatCardModule,
    MatChipsModule,
    MatDialogModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSnackBarModule,
    MatStepperModule,
    MatTooltipModule,
    MatTableModule,
    MatPaginatorModule,
    MatSelectModule,
    MatExpansionModule,
    MatGridListModule,
    MatSlideToggleModule,
    MatProgressSpinnerModule,
    MatBottomSheetModule,
    MatSliderModule,
    MatAutocompleteModule,
    MatMenuModule,
    MatCheckboxModule,
    MatButtonToggleModule,
    MatIconModule,
    MatBadgeModule
} from '@angular/material';

import { MatProgressBarModule } 
from '@angular/material/progress-bar';

@NgModule({
    imports: [
        CommonModule,
        MatButtonModule,
        MatToolbarModule,
        MatSidenavModule,
        BrowserAnimationsModule,
        MatInputModule,
        MatFormFieldModule,
        MatDividerModule,
        MatListModule,
        MatTabsModule,
        MatCardModule,
        MatChipsModule,
        MatDialogModule,
        MatProgressBarModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatSnackBarModule,
        MatStepperModule,
        MatTooltipModule,
        MatTableModule,
        MatPaginatorModule,
        MatSelectModule,
        MatExpansionModule,
        MatGridListModule,
        MatSlideToggleModule,
        LayoutModule,
        MatProgressSpinnerModule,
        MatBottomSheetModule,
        MatSliderModule,
        MatAutocompleteModule,
        MatMenuModule,
        MatCheckboxModule,
        MatButtonToggleModule,
        OverlayModule,
        MatIconModule,
        MatBadgeModule
    ],
    exports: [
        MatButtonModule,
        MatToolbarModule,
        MatSidenavModule,
        MatInputModule,
        MatFormFieldModule,
        MatDividerModule,
        MatListModule,
        MatTabsModule,
        MatCardModule,
        MatChipsModule,
        MatDialogModule,
        MatProgressBarModule,
        MatDatepickerModule,
        MatSnackBarModule,
        MatStepperModule,
        MatTooltipModule,
        MatTableModule,
        MatPaginatorModule,
        MatSelectModule,
        MatExpansionModule,
        MatGridListModule,
        MatSlideToggleModule,
        LayoutModule,
        MatProgressSpinnerModule,
        MatBottomSheetModule,
        MatSliderModule,
        MatAutocompleteModule,
        MatMenuModule,
        MatCheckboxModule,
        MatButtonToggleModule,
        OverlayModule,
        MatIconModule,
        MatBadgeModule
    ],
    declarations: []
})
export class MaterialModule { }